USE MASTER

GO

CREATE DATABASE MATRICULA_2025

GO
USE MATRICULA_2025

GO

CREATE TABLE PERIODOS (
                ID_PERIODO INT IDENTITY(1,1) NOT NULL,
                NUM_PERIODO TINYINT NOT NULL,
                ANIO SMALLINT NOT NULL,
                FECHAI_MATRICULA DATE NOT NULL,
                FECHAF_MATRICULA DATE NOT NULL,
                FECHAI_EXTRAORDINARIO DATE NOT NULL,
                FECHAF_EXTRAORDINARIO DATE NOT NULL,
                CONSTRAINT PK_PERIODOS PRIMARY KEY (ID_PERIODO)
)

CREATE TABLE MATERIAS (
                ID_MATERIA VARCHAR(10) NOT NULL,
                NOMBRE_MATERIA VARCHAR(120) NOT NULL,
                CREDITOS TINYINT NOT NULL,
                BORRADO BIT DEFAULT 0 NOT NULL,
                CONSTRAINT PK_MATERIAS PRIMARY KEY (ID_MATERIA)
)

CREATE TABLE PROFESORES (
                COD_PROFESOR INT IDENTITY(1,1) NOT NULL,
                ID_PROFESOR VARCHAR(20) NOT NULL,
                NOMBRE_P VARCHAR(25) NOT NULL,
                APELLIDO1_P VARCHAR(20) NOT NULL,
                APELLIDO2_P VARCHAR(20),
                TELEFONO_P VARCHAR(8) NOT NULL,
                CORREO_P VARCHAR(25) NOT NULL,
                ESTADO_P VARCHAR(3) DEFAULT 'ACT' NOT NULL,
                BORRADO BIT DEFAULT 0 NOT NULL,
                CONSTRAINT PK_PROFESORES PRIMARY KEY (COD_PROFESOR)
)

CREATE TABLE ESTUDIANTES (
                ID_ESTUDIANTE VARCHAR(20) NOT NULL,
                NOMBRE_E VARCHAR(25) NOT NULL,
                APELLIDO1_E VARCHAR(20) NOT NULL,
                APELLIDO2_E VARCHAR(20),
                TELEFONO1_E VARCHAR(8) NOT NULL,
                TELEFONO2_E VARCHAR(8),
                CORREO_E VARCHAR(25) NOT NULL,
                PROVINCIA VARCHAR(12) NOT NULL DEFAULT 'ALAJUELA',
                CANTON VARCHAR(20),
                DISTRITO VARCHAR(25),
                OTRAS_SENIAS VARCHAR(80),
                FECHA_NACIMIENTO DATE NOT NULL,
                FECHA_INGRESO DATE NOT NULL,
                ESTADO_E VARCHAR(3) NOT NULL DEFAULT 'ACT',
                BORRADO BIT DEFAULT 0 NOT NULL,
                CONSTRAINT PK_ESTUDIANTES PRIMARY KEY (ID_ESTUDIANTE)
)

CREATE TABLE MATRICULAS (
                NUM_RECIBO INT IDENTITY(1,1) NOT NULL,
                ID_ESTUDIANTE VARCHAR(20) NOT NULL,
                FECHA_MATRICULA DATETIME NOT NULL,
                ID_PERIODO INT NOT NULL,
                COSTO_MATRICULA DECIMAL(10,2) NOT NULL,
                DESCUENTO DECIMAL(4,2) DEFAULT 0 NOT NULL,
                ESTADO_M VARCHAR(3) NOT NULL DEFAULT 'ACT',
                CONSTRAINT PK_MATRICULAS PRIMARY KEY (NUM_RECIBO)
)

CREATE TABLE CARRERAS (
                ID_CARRERA INT IDENTITY(1,1) NOT NULL,
                NOMBRE_CARRERA VARCHAR(100) NOT NULL,
                TOTAL_CREDITOS SMALLINT NOT NULL,
                GRADO VARCHAR(14) DEFAULT 'BACHILLERATO' NOT NULL,
                ESTADO_C VARCHAR(3) DEFAULT 'ACT' NOT NULL,
                BORRADO BIT DEFAULT 0 NOT NULL,
                CONSTRAINT PK_CARRERAS PRIMARY KEY (ID_CARRERA)
)

CREATE TABLE MATERIAS_CARRERAS (
                ID_MATERIA_CARRERA INT IDENTITY(1,1) NOT NULL,
                ID_CARRERA INT NOT NULL,
                ID_MATERIA VARCHAR(10) NOT NULL,
                BORRADO BIT DEFAULT 0 NOT NULL,
                REQUISITO VARCHAR(10) NULL,
                CONSTRAINT PK_MATERIAS_CARRERAS PRIMARY KEY (ID_MATERIA_CARRERA)
)

CREATE TABLE MATERIAS_ABIERTAS (
                ID_MATERIA_ABIERTA INT IDENTITY(1,1) NOT NULL,
                GRUPO TINYINT NOT NULL,
                CUPO TINYINT NOT NULL,
                COSTO DECIMAL(10,2) NOT NULL,
                DESCUENTO DECIMAL(4,2) DEFAULT 0 NOT NULL,
                CANT_MATRICULADOS TINYINT DEFAULT 0 NOT NULL,
                ID_PERIODO INT NOT NULL,
                COD_PROFESOR INT NULL,
                ID_MATERIA_CARRERA INT NOT NULL,
				ID_AULA INT NULL
                CONSTRAINT PK_MATERIAS_ABIERTAS PRIMARY KEY (ID_MATERIA_ABIERTA)
)

CREATE TABLE DETALLES_MATRICULA (
                NUM_RECIBO INT NOT NULL,
                ID_MATERIA_ABIERTA INT NOT NULL,
                NOTA_FINAL DECIMAL(5,2) DEFAULT 0 NOT NULL,
                ESTADO_D VARCHAR(3) NOT NULL DEFAULT 'ACT',
                OBSERVACIONES VARCHAR(500),
				CONSTRAINT PK_DETALLES_MATRICULA PRIMARY KEY (NUM_RECIBO,ID_MATERIA_ABIERTA)
)

CREATE TABLE HORARIOS (
                ID_MATERIA_ABIERTA INT NOT NULL,
                DIA VARCHAR NOT NULL,
                HORA_INICIO TIME NOT NULL,
                HORA_FIN TIME NOT NULL,
                CONSTRAINT PK_HORARIOS PRIMARY KEY (ID_MATERIA_ABIERTA, DIA, HORA_INICIO, HORA_FIN)
)

CREATE TABLE AULAS (
                ID_AULA INT IDENTITY(1,1) NOT NULL,
                CAPACIDAD SMALLINT NOT NULL,
                TIPO VARCHAR(20) NOT NULL,
                CONSTRAINT PK_AULAS PRIMARY KEY (ID_AULA)
)

-- FOREIGN KEY

ALTER TABLE MATERIAS_ABIERTAS ADD CONSTRAINT PERIODOS_MATERIAS_ABIERTAS_fk
FOREIGN KEY (ID_PERIODO)
REFERENCES PERIODOS (ID_PERIODO)
ON DELETE NO ACTION
ON UPDATE NO ACTION

ALTER TABLE MATERIAS_ABIERTAS ADD CONSTRAINT PROFESORES_MATERIAS_ABIERTAS_fk
FOREIGN KEY (COD_PROFESOR)
REFERENCES PROFESORES (COD_PROFESOR)

ALTER TABLE MATERIAS_ABIERTAS ADD CONSTRAINT AULAS_MATERIAS_ABIERTAS_fk
FOREIGN KEY (ID_AULA)
REFERENCES AULAS (ID_AULA)


ALTER TABLE MATERIAS_ABIERTAS ADD CONSTRAINT MATERIAS_CARRERAS_MATERIAS_ABIERTAS_fk
FOREIGN KEY (ID_MATERIA_CARRERA)
REFERENCES MATERIAS_CARRERAS (ID_MATERIA_CARRERA)


ALTER TABLE MATRICULAS ADD CONSTRAINT PERIODOS_MATRICULAS_fk
FOREIGN KEY (ID_PERIODO)
REFERENCES PERIODOS (ID_PERIODO)


ALTER TABLE MATRICULAS ADD CONSTRAINT ESTUDIANTES_MATRICULAS_fk
FOREIGN KEY (ID_ESTUDIANTE)
REFERENCES ESTUDIANTES (ID_ESTUDIANTE)


ALTER TABLE MATERIAS_CARRERAS ADD CONSTRAINT MATERIAS_MATERIAS_CARRERAS_fk
FOREIGN KEY (ID_MATERIA)
REFERENCES MATERIAS (ID_MATERIA)


ALTER TABLE MATERIAS_CARRERAS ADD CONSTRAINT CARRERAS_MATERIAS_CARRERAS_fk
FOREIGN KEY (ID_CARRERA)
REFERENCES CARRERAS (ID_CARRERA)


ALTER TABLE MATERIAS_CARRERAS ADD CONSTRAINT MATERIAS_CARRERAS_REQUISITO_fk
FOREIGN KEY (REQUISITO)
REFERENCES MATERIAS (ID_MATERIA)


ALTER TABLE DETALLES_MATRICULA ADD CONSTRAINT MATRICULAS_DETALLES_MATRICULA_fk
FOREIGN KEY (NUM_RECIBO)
REFERENCES MATRICULAS (NUM_RECIBO)


ALTER TABLE DETALLES_MATRICULA ADD CONSTRAINT MATERIAS_ABIERTAS_DETALLES_MATRICULA_fk
FOREIGN KEY (ID_MATERIA_ABIERTA)
REFERENCES MATERIAS_ABIERTAS (ID_MATERIA_ABIERTA)


ALTER TABLE HORARIOS ADD CONSTRAINT MATERIAS_ABIERTAS_HORARIOS_fk
FOREIGN KEY (ID_MATERIA_ABIERTA)
REFERENCES MATERIAS_ABIERTAS (ID_MATERIA_ABIERTA)


--Restricciones check

alter table CARRERAS
   add constraint CK_GRADO_CARRERA check (Grado in ('Diplomado','Bachillerato','Licenciatura','Maestría'))

alter table CARRERAS
   add constraint CK_TOTAL_CREDITOS_CARRERA check (Total_Creditos >= 0 and Total_Creditos<=1000)

alter table CARRERAS
   add constraint CK_ESTADO_CARRERA check (ESTADO_C in ('ACT','INA') and ESTADO_C = upper(ESTADO_C))

alter table PROFESORES
   add constraint CK_ESTADO_PROFESOR check (ESTADO_P in ('ACT','INA') and ESTADO_P = upper(ESTADO_P))


alter table Estudiantes
   add constraint CK_ESTADO_ESTUDIAN check (ESTADO_E in ('ACT','INA') and ESTADO_E = upper(ESTADO_E))


alter table Estudiantes
   add constraint CK_provincia_est check (Provincia is null or 
   (Provincia in ('San José','Alajuela','Heredia','Cartago','Guanacaste','Puntarenas','Limón')))

alter table Materias
   add constraint CKC_CANTIDAD_CREDITOS check (CREDITOS between 0 and 12)


alter table Horarios
   add constraint CK_DIA_HORARIO_ check (DIA in ('L','K','M','J','V','S') and DIA = upper(DIA))


alter table PERIODOS
   add constraint CKC_PERIODO check (NUM_PERIODO between 1 and 3)


alter table Materias_Abiertas
   add constraint CKC_COSTO_MATERIA_ check (COSTO > 0)

alter table Materias_Abiertas
   add constraint CKC_DESCUENTO_MATERIA_ check (DESCUENTO >= 0 AND DESCUENTO<=100)

alter table PERIODOS
   add constraint CKC_anio check (ANIO >= Year(getDate()))


alter table Matriculas
   add constraint CKC_COSTO_MATRICULA check (COSTO_MATRICULA >= 0)

alter table Matriculas
   add constraint CKC_DESCUENTO_MATRICULA check (DESCUENTO >= 0 AND DESCUENTO<=100)


alter table Matriculas
   add constraint CKC_ESTADO_MATRICUL check (ESTADO_M in ('Act','Ina','Anu'))


alter table Detalles_Matricula
   add constraint CK_ESTADO_DETALLE_ check (Estado_D in ('ACT','RET','APR','REP','DST') and ESTADO_D = upper(ESTADO_D))


alter table Detalles_Matricula
   add constraint CK_NOTA_FINAL_DETALLE_ check (Nota_Final is null or (Nota_Final BETWEEN 0 and 100))


  INSERT INTO CARRERAS (NOMBRE_CARRERA, TOTAL_CREDITOS, GRADO, ESTADO_C)
VALUES 
('INGENIERIA CIVIL', 0, 'BACHILLERATO', 'ACT'),
('INGENIERIA EN MANEJO DE RECURSO HIDRICO', 0, 'BACHILLERATO', 'ACT'),
('INGENIERIA EN SISTEMAS DE INFORMACION', 0, 'BACHILLERATO', 'ACT'),
('INGENIERIA QUIMICA', 0, 'LICENCIATURA', 'ACT');

INSERT INTO ESTUDIANTES 
(ID_ESTUDIANTE, NOMBRE_E, APELLIDO1_E, APELLIDO2_E, TELEFONO1_E, CORREO_E, PROVINCIA, FECHA_NACIMIENTO, FECHA_INGRESO, ESTADO_E)
VALUES
('2-1111-1111', 'ANA', 'GOMEZ', 'ARTAVIA', '87212356', 'ana@mail.com', 'ALAJUELA', '2000-03-12', '2017-01-20', 'ACT'),
('2-2222-1111', 'PATRICIA', 'SALAS', 'FUENTES', '86564878', 'patricia@mail.com', 'ALAJUELA', '2003-05-02', '2019-01-20', 'ACT'),
('2-3333-1111', 'RODRIGO', 'ARCE', 'MORA', '87114578', 'rodrigo@mail.com', 'ALAJUELA', '2001-08-19', '2018-01-20', 'ACT'),
('2-4444-1111', 'GUSTAVO', 'LORIA', 'ROJAS', '88974154', 'gustavo@mail.com', 'ALAJUELA', '2005-08-11', '2020-01-20', 'ACT'),
('2-5555-1111', 'JUAN CARLOS', 'GONZALEZ', 'SOLIS', '86458978', 'juan@mail.com', 'ALAJUELA', '2003-04-22', '2021-01-20', 'ACT');

INSERT INTO PROFESORES 
(ID_PROFESOR, NOMBRE_P, APELLIDO1_P, APELLIDO2_P, TELEFONO_P, CORREO_P, ESTADO_P)
VALUES
('3-5555-2222', 'JUAN JOSE', 'GONZALEZ', 'CAMPOS', '85666699', 'NO REGISTRA', 'ACT'),
('3-1111-2222', 'ROBERTO', 'SOTO', 'ARIAS', '87111122', 'NO REGISTRA', 'ACT'),
('3-2121-2222', 'CARMEN', 'RETANA', 'OCAMPO', '85666611', 'NO REGISTRA', 'ACT'),
('3-1313-2222', 'LAURA', 'FERNANDEZ', 'MATA', '85666600', 'NO REGISTRA', 'ACT'),
('3-4141-2222', 'GERARDO', 'GONZALEZ', 'LOBO', '85116699', 'NO REGISTRA', 'ACT');

INSERT INTO PERIODOS (NUM_PERIODO, ANIO, FECHAI_MATRICULA, FECHAF_MATRICULA, FECHAI_EXTRAORDINARIO, FECHAF_EXTRAORDINARIO)
VALUES 
(2, 2025, '2024-06-20', '2024-07-30', '2024-07-20', '2024-07-21');

INSERT INTO MATERIAS(ID_MATERIA, NOMBRE_MATERIA,      CREDITOS, BORRADO) VALUES 
('AC-100', 'ACTIVIDAD CULTURAL', 4, 0),
('FH-100', 'FORMACION HUMANISTICA', 6, 0),
('IC0302', 'DISEÑO GRAFICO', 4, 0),
('IS0101', 'MECÁNICA DEL SÓLIDO I', 4, 0),
('IQ0332', 'ANALISIS DE PROCESOS', 4, 0),
('IQ0503', 'QUIMICA ANALITICA', 6, 0),
('IRH012', 'MANEJO INTEGRAL DEL RECURSO HIDRICO', 4, 0),
('IRH013', 'MANEJO DE RESIDUOS SOLIDOS', 6, 0),
('ISI712', 'TECNOLOGIAS Y SISTEMAS WEB', 4, 0),
('ISI713', 'DISEÑO DE REDES',0,0);

INSERT INTO MATERIAS_CARRERAS (ID_CARRERA, ID_MATERIA, BORRADO, REQUISITO) VALUES 
(1, 'AC-100', 0, NULL),
(1, 'AC-100', 0, NULL),
(1, 'AC-100', 0, NULL),
(1, 'FH-100', 0, NULL),
(1, 'FH-100', 0, NULL),
(1, 'IC0302', 0, NULL),
(1, 'IS0101', 0, NULL),
(1, 'IQ0332', 0, NULL),
(1, 'IQ0503', 0, NULL),
(1, 'IRH012', 0, NULL),
(1, 'IRH013', 0, NULL),
(1, 'ISI712', 0, NULL),
(1, 'ISI713', 0, NULL),
(1, 'AC-100', 0, NULL),
(1, 'FH-100', 0, NULL);
INSERT INTO MATERIAS_ABIERTAS (GRUPO, CUPO, COSTO, DESCUENTO, CANT_MATRICULADOS, ID_PERIODO, COD_PROFESOR, ID_MATERIA_CARRERA)
VALUES 
(1, 20, 50000.00, 0.00, 0, 4, 1, 1),
(1, 20, 50000.00, 0.00, 0, 4, 2, 2),
(1, 20, 50000.00, 0.00, 0, 4, 3, 3),
(2, 20, 50000.00, 0.00, 0, 4, 2, 3),
(1, 20, 50000.00, 0.00, 0, 4, 4, 13),
(1, 20, 50000.00, 0.00, 0, 4, 5, 15),
(1, 20, 50000.00, 0.00, 0, 4, 1, 12);

INSERT INTO HORARIOS (ID_MATERIA_ABIERTA, DIA, HORA_INICIO, HORA_FIN) VALUES
(3, 'L', '14:00:00', '16:00:00'),
(3, 'M', '14:00:00', '16:00:00'),
(4, 'L', '15:00:00', '18:00:00'),
(5, 'J', '13:00:00', '17:00:00'),
(6, 'J', '08:00:00', '10:30:00'),
(6, 'K', '08:00:00', '10:30:00'),
(7, 'L', '08:00:00', '10:30:00'),
(7, 'V', '08:00:00', '10:30:00'),
(8, 'L', '09:00:00', '13:45:00'),
(9, 'J', '14:00:00', '17:00:00'),
(9, 'K', '14:00:00', '17:00:00');

INSERT INTO AULAS (CAPACIDAD, TIPO) VALUES (30, 'Taller');
INSERT INTO AULAS (CAPACIDAD, TIPO) VALUES (30, 'Laboratorio');
INSERT INTO AULAS (CAPACIDAD, TIPO) VALUES (30, 'Salón');

UPDATE estudiantes
SET provincia = 'Alajuela', canton = 'Central'
WHERE provincia IS NULL or CANTON is null;

SELECT *
FROM carreras
WHERE GRADO IN ('bachillerato', 'Licenciatura');

SELECT *
FROM CARRERAS
WHERE NOMBRE_CARRERA LIKE 'INGENIERIA%';


SELECT MATERIAS_CARRERAS.*, CARRERAS.NOMBRE_CARRERA
FROM MATERIAS_CARRERAS
JOIN CARRERAS
  ON MATERIAS_CARRERAS.ID_CARRERA = CARRERAS.ID_CARRERA
WHERE CARRERAS.NOMBRE_CARRERA = 'Ingenieria Civil';


SELECT 
  MATERIAS.*, 
  CARRERAS.NOMBRE_CARRERA
FROM MATERIAS_CARRERAS
JOIN CARRERAS 
  ON MATERIAS_CARRERAS.ID_CARRERA = CARRERAS.ID_CARRERA
JOIN MATERIAS 
  ON MATERIAS_CARRERAS.ID_MATERIA = MATERIAS.ID_MATERIA
WHERE CARRERAS.NOMBRE_CARRERA = 'Ingenieria Quimica'
  AND MATERIAS.CREDITOS > 3;

SELECT *
FROM MATERIAS
WHERE CREDITOS BETWEEN 3 AND 6;


SELECT
  C.NOMBRE_CARRERA,
  M.NOMBRE_MATERIA,
  M.CREDITOS,
  MC.BORRADO,
  MC.REQUISITO
FROM MATERIAS_CARRERAS MC
JOIN CARRERAS C
  ON MC.ID_CARRERA = C.ID_CARRERA
JOIN MATERIAS M
  ON MC.ID_MATERIA = M.ID_MATERIA
WHERE MC.REQUISITO IS NULL
   OR MC.REQUISITO = '';

   SELECT
  C.NOMBRE_CARRERA,
  M.ID_MATERIA,
  M.NOMBRE_MATERIA,
  M.CREDITOS,
  MC.REQUISITO AS ID_REQUISITO,
  Pre.NOMBRE_MATERIA AS NOMBRE_REQUISITO
FROM MATERIAS_CARRERAS MC
JOIN CARRERAS C
  ON MC.ID_CARRERA = C.ID_CARRERA
JOIN MATERIAS M
  ON MC.ID_MATERIA = M.ID_MATERIA
JOIN MATERIAS Pre
  ON MC.REQUISITO = Pre.ID_MATERIA
WHERE Pre.NOMBRE_MATERIA LIKE '%Informática%';

SELECT *
FROM PROFESORES
WHERE NOMBRE_P LIKE '%A'
ORDER BY APELLIDO1_P;


SELECT *
FROM PROFESORES
ORDER BY APELLIDO1_P, APELLIDO2_P;


SELECT *
FROM ESTUDIANTES
WHERE YEAR(FECHA_INGRESO) = YEAR(GETDATE());

SELECT *
FROM ESTUDIANTES
WHERE APELLIDO1_E COLLATE Latin1_General_CI_AS LIKE 'ar%'


SELECT *
FROM ESTUDIANTES
WHERE APELLIDO1_E LIKE 'Ar'  
ORDER BY NOMBRE_E;

UPDATE ESTUDIANTES
SET OTRAS_SENIAS = 'INACTIVO'
WHERE NOMBRE_E COLLATE Latin1_General_CI_AS LIKE 'j%';
select * from ESTUDIANTES

SELECT *
FROM MATERIAS_ABIERTAS
WHERE COSTO > 40000;








select * from MATERIAS







